// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -source=./interface.go -destination=./mock/interface_generated.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v2alpha1 "github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteInterface is a mock of DeleteInterface interface.
type MockDeleteInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteInterfaceMockRecorder
	isgomock struct{}
}

// MockDeleteInterfaceMockRecorder is the mock recorder for MockDeleteInterface.
type MockDeleteInterfaceMockRecorder struct {
	mock *MockDeleteInterface
}

// NewMockDeleteInterface creates a new mock instance.
func NewMockDeleteInterface(ctrl *gomock.Controller) *MockDeleteInterface {
	mock := &MockDeleteInterface{ctrl: ctrl}
	mock.recorder = &MockDeleteInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteInterface) EXPECT() *MockDeleteInterfaceMockRecorder {
	return m.recorder
}

// DeleteRegistryImages mocks base method.
func (m *MockDeleteInterface) DeleteRegistryImages(images v2alpha1.DeleteImageList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistryImages", images)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistryImages indicates an expected call of DeleteRegistryImages.
func (mr *MockDeleteInterfaceMockRecorder) DeleteRegistryImages(images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistryImages", reflect.TypeOf((*MockDeleteInterface)(nil).DeleteRegistryImages), images)
}

// ReadDeleteMetaData mocks base method.
func (m *MockDeleteInterface) ReadDeleteMetaData() (v2alpha1.DeleteImageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDeleteMetaData")
	ret0, _ := ret[0].(v2alpha1.DeleteImageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDeleteMetaData indicates an expected call of ReadDeleteMetaData.
func (mr *MockDeleteInterfaceMockRecorder) ReadDeleteMetaData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDeleteMetaData", reflect.TypeOf((*MockDeleteInterface)(nil).ReadDeleteMetaData))
}

// WriteDeleteMetaData mocks base method.
func (m *MockDeleteInterface) WriteDeleteMetaData(arg0 []v2alpha1.CopyImageSchema) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteDeleteMetaData", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteDeleteMetaData indicates an expected call of WriteDeleteMetaData.
func (mr *MockDeleteInterfaceMockRecorder) WriteDeleteMetaData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteDeleteMetaData", reflect.TypeOf((*MockDeleteInterface)(nil).WriteDeleteMetaData), arg0)
}
