FROM quay.io/openshifttest/registry

# Layer 1
RUN touch /layer1 && echo "Layer 1" > /layer1

# Layer 2
RUN touch /layer2 && echo "Layer 2" > /layer2

# Layer 3
RUN touch /layer3 && echo "Layer 3" > /layer3

# Layer 4
RUN touch /layer4 && echo "Layer 4" > /layer4

# Layer 5
RUN touch /layer5 && echo "Layer 5" > /layer5

# Layer 6
RUN touch /layer6 && echo "Layer 6" > /layer6

# Layer 7
RUN touch /layer7 && echo "Layer 7" > /layer7

# Layer 8
RUN touch /layer8 && echo "Layer 8" > /layer8

# Layer 9
RUN touch /layer9 && echo "Layer 9" > /layer9

# Layer 10
RUN touch /layer10 && echo "Layer 10" > /layer10
