# This example demonstrates how to mirror a helm chart
# and all referenced images within that chart. A version
# must be specified for the chart. Charts can alternatively
# be mirrored from local sources, as seen in the commented
# portion of this example.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  helm:
    repositories:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
    #local:
    #  - name: podinfo-local
    #    path: /home/user/podinfo-6.0.0.tgz
