# This config uses the headsOnly feature which will mirror the 
# latest version of each channel within each package contained 
# within a specified operator catalog.

# IMPORTANT: When using headsOnly mode, the latest (HEAD) version is mirrored for each channel in each operator package
# when metadata is first written. On subsequent runs, the operator package channel bundles are mirrored
# from the previous channel head to the current channel head.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10