# This config demonstrates how to mirror a version range
# in the specified channel for an OpenShift release.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    architectures:
      - "s390x" # Valid values are: amd64(default), arm64, ppc64le, s390x and multi.
    channels:
      - name: stable-4.9
        minVersion: 4.9.13
        maxVersion: 4.9.26