{{range .}}
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    architectures:
      - "multi"
      - "ppc64le"
      - "amd64"
    channels:
    - name: {{.}} 
    graph: true
{{end}}