package cli

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/openshift/oc-mirror/v2/internal/pkg/api/v2alpha1"
	"github.com/openshift/oc-mirror/v2/internal/pkg/emoji"
)

func (o *ExecutorSchema) DryRun(ctx context.Context, allImages []v2alpha1.CopyImageSchema) error {
	// set up location of logs dir
	outDir := filepath.Join(o.Opts.Global.WorkingDir, dryRunOutDir)
	// clean up logs directory
	os.RemoveAll(outDir)

	// create logs directory
	err := o.MakeDir.makeDirAll(outDir, 0755)
	if err != nil {
		o.Log.Error(" %v ", err)
		return err
	}
	// creating file for storing list of cached images
	mappingTxtFilePath := filepath.Join(outDir, mappingFile)
	mappingTxtFile, err := os.Create(mappingTxtFilePath)
	if err != nil {
		return err
	}
	defer mappingTxtFile.Close()
	imagesAvailable := map[string]bool{}
	nbMissingImgs := 0
	var buff bytes.Buffer
	var missingImgsBuff bytes.Buffer
	for _, img := range allImages {
		buff.WriteString(img.Source + "=" + img.Destination + "\n")
		if o.Opts.IsMirrorToDisk() {
			exists, err := o.Mirror.Check(ctx, img.Destination, o.Opts, false)
			if err != nil {
				o.Log.Debug("unable to check existence of %s in local cache: %v", img.Destination, err)
			}
			if err != nil || !exists {
				missingImgsBuff.WriteString(img.Source + "=" + img.Destination + "\n")
				nbMissingImgs++
			}
		}
	}

	_, err = mappingTxtFile.Write(buff.Bytes())
	if err != nil {
		return err
	}
	if nbMissingImgs > 0 {
		// creating file for storing list of cached images
		missingImgsFilePath := filepath.Join(outDir, missingImgsFile)
		missingImgsTxtFile, err := os.Create(missingImgsFilePath)
		if err != nil {
			return err
		}
		defer missingImgsTxtFile.Close()
		_, err = missingImgsTxtFile.Write(missingImgsBuff.Bytes())
		if err != nil {
			return err
		}
		o.Log.Warn(emoji.Warning+"  %d/%d images necessary for mirroring are not available in the cache.", nbMissingImgs, len(allImages))
		o.Log.Warn("List of missing images in : %s.\nplease re-run the mirror to disk process", missingImgsFilePath)
	}

	if len(imagesAvailable) > 0 {
		o.Log.Info("all %d images required for mirroring are available in local cache. You may proceed with mirroring from disk to disconnected registry", len(imagesAvailable))
	}
	o.Log.Info(emoji.PageFacingUp+" list of all images for mirroring in : %s", mappingTxtFilePath)

	// Generate cluster resources in dry-run mode
	if err := o.generateClusterResourcesForDryRun(allImages); err != nil {
		return err
	}

	return nil
}

// generateClusterResourcesForDryRun generates all cluster resources that would be created during mirroring
func (o *ExecutorSchema) generateClusterResourcesForDryRun(allImages []v2alpha1.CopyImageSchema) error {
	// Skip cluster resource generation if ClusterResources is not initialized (e.g., in tests)
	if o.ClusterResources == nil {
		o.Log.Debug("ClusterResources not initialized, skipping cluster resource generation")
		return nil
	}

	o.Log.Info(emoji.PageFacingUp + " Generating cluster resources...")

	// create IDMS/ITMS
	forceRepositoryScope := o.Opts.Global.MaxNestedPaths > 0
	if err := o.ClusterResources.IDMS_ITMSGenerator(allImages, forceRepositoryScope); err != nil {
		return err
	}

	// create catalog source
	if err := o.ClusterResources.CatalogSourceGenerator(allImages); err != nil {
		return err
	}

	if err := o.ClusterResources.ClusterCatalogGenerator(allImages); err != nil {
		return err
	}

	// generate signature config map
	if err := o.ClusterResources.GenerateSignatureConfigMap(allImages); err != nil {
		// as this is not a seriously fatal error we just log the error
		o.Log.Warn("%s", err)
	}

	// Generate UpdateService if we have release images
	hasReleaseImages := false
	var releaseImage string
	for _, img := range allImages {
		if img.Type == v2alpha1.TypeOCPRelease {
			hasReleaseImages = true
			releaseImage = img.Origin
			break
		}
	}

	if hasReleaseImages {
		// We need to generate a graph image reference for the update service
		// In dry-run mode, we'll use a placeholder or construct the expected reference
		graphImageRef, err := o.constructGraphImageRef(releaseImage)
		if err != nil {
			return err
		}
		if err := o.ClusterResources.UpdateServiceGenerator(graphImageRef, releaseImage); err != nil {
			return err
		}
	}

	return nil
}

// constructGraphImageRef constructs the graph image reference that would be used for UpdateService
func (o *ExecutorSchema) constructGraphImageRef(releaseImageRef string) (string, error) {
	// In the normal workflow, the graph image is generated by Release.GraphImage()
	// For dry-run, we need to construct what the reference would be
	releaseImageParts := strings.Split(releaseImageRef, "/")
	if len(releaseImageParts) < 3 {
		return "", fmt.Errorf("invalid release image reference: %s", releaseImageRef)
	}

	// Extract destination registry information from the first image
	var destinationRegistry string
	for _, img := range o.Config.ImageSetConfigurationSpec.Mirror.AdditionalImages {
		if strings.Contains(img.Name, "/") {
			// This is a placeholder - in actual implementation, we'd use the destination registry
			// For now, we'll use localhost as placeholder for dry-run
			destinationRegistry = "localhost:5000"
			break
		}
	}

	if destinationRegistry == "" {
		destinationRegistry = "localhost:5000" // Default for dry-run
	}

	// Construct the graph image reference
	graphImageRef := fmt.Sprintf("%s/openshift/graph-data:latest", destinationRegistry)
	return graphImageRef, nil
}
